### ISSUE TITLE
Write python3 tests

### ISSUE THREAD

**Issue by jwcooper** [adafruit/adafruit-beaglebone-io-python#10]

**Comment by pdp7** [comment]
@jwcooper Is this still needed?  @matthewwest did some Python3 compatibility in #108

**Comment by MatthewWest** [comment]
Just to chime in here - it's running fine on either Python 2 or 3. What was being thought of for tests of Python 3 in particular?

**Comment by pdp7** [comment]
@jwcooper is this issue still needed?
