### ISSUE TITLE
[feature] Add a get_fd() method

### ISSUE THREAD

**Issue by lromor** [adafruit/adafruit-beaglebone-io-python#112]
Hello, 
I think it could be interesting to retrieve the file descriptor of a GPIO, mostly for custom python event detects, (for example, asyncio add_reader, select, poll, etc..).

I already added this feature on my fork, but i'm pretty sure it's far from being optimal.

let me know what you think. 

-l

**Comment by pdp7** [comment]
Please create a pull request and I'll try it out.

**Comment by pdp7** [comment]
@lromor thanks for the PR. Is there a test that could be added for this in tests?
