### ISSUE TITLE
File descriptor leak in gpio_get_direction

### ISSUE THREAD

**Issue by ltjax** [adafruit/adafruit-beaglebone-io-python#140]
Found this while hunting for my memory leak. It wasn't it, but it should probably still be fixed:

In event.gpio.c, function gpio_get_direction the file descriptor is never closed.

**Comment by pdp7** [comment]
@ltjax thanks.  Would you be able to submit a pull request?

**Comment by ltjax** [comment]
Right now I'm on a tight time budget, so I can't really promise it. Might be faster if you just fixed it yourself.

**Comment by pdp7** [comment]
@ltjax thanks for reporting this.  resolved by commit da0b0e5
