### ISSUE TITLE
 IOError: [Errno 2] No such file or directory: '/slots'. 

### ISSUE THREAD

**Issue by Rohi23** [adafruit/adafruit-beaglebone-io-python#167]
Hello , 

I am new to beagle bone. 
 I am trying to run pwm program. But getting
 IOError: [Errno 2] No such file or directory: '/slots'. 

Below is the program .

import Adafruit_BBIO.PWM as PWM
#PWM.start(channel, duty, freq=2000, polarity=0)
PWM.start("P9_14", 50)

PWM.set_duty_cycle("P9_14", 25.5)
PWM.set_frequency("P9_14", 10)
PWM.stop("P9_14")
PWM.cleanup()

When i run getting below error. 

 File "pwm.py", line 5, in <module>
    PWM.set_duty_cycle("P9_14", 25.5)
IOError: [Errno 2] No such file or directory: '/slots'

Please advice.

**Comment by RobertCNelson** [comment]
@Rohi23 please run:

```
sudo /opt/scripts/tools/version.sh
```

@pdp7 with later u-boot and kernel combinations, the "slots" file is now disabled when running u-boot overlays. (this was changed to stop users from echoing into "slots" and locking up the system)..

So the "bone_capemgr" directory is still there:

```
/sys/devices/platform/bone_capemgr/
```
While this file only exists if the old "kernel" overlays method is active (non-u-boot-overlays)
```
/sys/devices/platform/bone_capemgr/slots
```
Regards,

**Comment by pdp7** [comment]
Thanks @RobertCNelson 

@Rohi23 if `/opt/scripts/tools/version.sh` does not exist, then please paste the output of these two commands:
```
uname -a

cat /etc/dogtag
```

**Comment by Rohi23** [comment]
Hi pdp7. 

Not able to execute
sudo /opt/scripts/tools/version.sh

Below is the output.

root@beaglebone:~# uname -a
Linux beaglebone 4.4.9-ti-r25 #1 SMP Thu May 5 23:08:13 UTC 2016 armv7l GNU/Linu                                                                                                                     x
root@beaglebone:~# cat /etc/dogtag
BeagleBoard.org Debian Image 2016-05-13
root@beaglebone:~#

**Comment by pdp7** [comment]
@Rohi23  that 2016-05-13 image is a bit old at this point.  Please download the latest image (Debian 9.1 2017-09-21 4GB SD IoT image) from http://beagleboard.org/latest-images

**Comment by pdp7** [comment]
@Rohi23 are you still having an issue?  Please let me know.  Thanks.

**Comment by pdp7** [comment]
@Rohi23 can I close this issue?

**Comment by pdp7** [comment]
@Rohi23 please reopen if still an issue

**Comment by ravinderreddy429** [comment]
hi,
 
I am working with the BBB, i would like to Enable SPI in BBB to connect SPI based timer PCF2129

I am getting the error below 

debian@beaglebone:~$ cat /sys/devices/platform/bone_capemgr/slots 
cat: /sys/devices/platform/bone_capemgr/slots: No such file or directory
debian@beaglebone:~$ sudo /opt/scripts/tools/version.sh
[sudo] password for debian: 
git:/opt/scripts/:[d36fe9a7be9ebfc872b10a470e904ab4c61c4516]
eeprom:[A335BNLT000C1633BBBG0061]
dogtag:[BeagleBoard.org Debian Image 2017-10-10]
bootloader:[microSD-(push-button)]:[/dev/mmcblk0]:[U-Boot 2017.09-00002-g0f3f1c7907]
bootloader:[eMMC-(default)]:[/dev/mmcblk1]:[U-Boot 2017.09-00002-g0f3f1c7907]
kernel:[4.4.91-ti-r133]
nodejs:[v6.11.4]
uboot_overlay_options:[enable_uboot_overlays=1]
uboot_overlay_options:[uboot_overlay_pru=/lib/firmware/AM335X-PRU-RPROC-4-4-TI-00A0.dtbo]
uboot_overlay_options:[enable_uboot_cape_universal=1]
pkg:[bb-cape-overlays]:[4.4.20171009.0-0rcnee1~stretch+20171009]
pkg:[bb-wl18xx-firmware]:[1.20170829-0rcnee1~stretch+20170829]
pkg:[firmware-ti-connectivity]:[20170823-1rcnee0~stretch+20170830]
debian@beaglebone:~$ cat /sys/devices/platform/bone_capemgr/slots
cat: /sys/devices/platform/bone_capemgr/slots: No such file or directory
debian@beaglebone:~$ uname -a
Linux beaglebone 4.4.91-ti-r133 #1 SMP Tue Oct 10 05:18:08 UTC 2017 armv7l GNU/Linux
debian@beaglebone:~$ cat /etc/dogtag
BeagleBoard.org Debian Image 2017-10-10

what can be th solution for this......

Regards,
Ravinderreddy

**Comment by RobertCNelson** [comment]
@ravinderreddy429 

add your cape overlay to /boot/uEnv.txt with:

https://elinux.org/Beagleboard:BeagleBoneBlack_Debian#U-Boot_Override_external_capes

regards,

**Comment by NagarjunaReddy1242** [comment]
i got one problem 
cat /sys/devices/platform/bone_capemgr/slots  its giving error as no such directory/file
can you please solve this error

**Comment by Dabsag** [comment]
@NagarjunaReddy1242 
open uEnv.txt /boot directory and comment out the line "enable_uboot_overlays=1"
It should look like this : "#enable_uboot_overlays=1"
This worked for me in Debian 9.2 IoT

**Comment by NagarjunaReddy1242** [comment]
hi Shantnav Agarwal i was try what your said but it is not slove. is there
any other solution

**Comment by NagarjunaReddy1242** [comment]
same error iam getting

**Comment by HLLNSTN** [comment]
uncommenting:
[code]enable_uboot_overlays=1[/code]
in [code]/boot/uEnv.txt[/code]
allowed me to get SPIDEV's [code]/dev/spidev1.0[/code] working on DEBIAN 9 - this is a very valuable if anyone is trying to run FLASHROM to install LIBREBOOT with a BEAGLEBONE BLACK

**Comment by HLLNSTN** [comment]
uncommenting:
`enable_uboot_overlays=1`
in /boot/uEnv.txt
allowed me to get SPIDEV's /dev/spidev1.0 working on DEBIAN 9 - this is a very valuable if anyone is trying to run FLASHROM to install LIBREBOOT with a BEAGLEBONE BLACK

**Comment by HLLNSTN** [comment]
uncommenting `enable_uboot_overlays=1`
in `/boot/uEnv.txt`
allowed me to get SPIDEV's `/dev/spidev1.0` working on DEBIAN 9 - this is a very valuable if anyone is trying to run FLASHROM to install LIBREBOOT with a BEAGLEBONE BLACK

**Comment by HLLNSTN** [comment]
uncommenting `enable_uboot_overlays=1`
in `/boot/uEnv.txt`
allowed me to get SPIDEV's /dev/spidev1.0 working on a BEAGLEBONE BLACK on DEBIAN 9 - this is probably very essential if you are trying to run `flashrom` to install LIBREBOOT, for example

**Comment by HLLNSTN** [comment]
uncommenting `enable_uboot_overlays=1`
in `/boot/uEnv.txt`
allowed me to get SPIDEV's `/dev/spidev1.0` working on a BEAGLEBONE BLACK on DEBIAN 9 - this is probably very essential if you are trying to run `flashrom` to install LIBREBOOT, for example

**Comment by salahgafoor** [comment]
Hi,

Please reopen this thread, if closed.

I want to configure some of my gpio pins (P8_07 to P8_10) of my beagle bone black revC board as inputs with active high state.

OS running in my board is Debian 9.3, with Kernel 4.1.

Thanks in advance!

**Comment by amirbenayed** [comment]
I dont find the file bone_capemgr in /sys/devices/platform/
