### ISSUE TITLE
I suspect GPO_3 is a typo and should be GP0_3 (numerical 0 instead of capital O)

### ISSUE THREAD

**Issue by randyrossi** [adafruit/adafruit-beaglebone-io-python#174]
https://github.com/adafruit/adafruit-beaglebone-io-python/blob/e981c59c6b080781c493cbb72dae63d330243890/source/common.c#L172

**Comment by RobertCNelson** [comment]
Correct that should be the number "0"...

**Comment by silver2row** [comment]
Hello,

Nice catch. 

Seth

P.S. Is the Adafruit_BBIO having issues still?

**Comment by RobertCNelson** [comment]
@silver2row which issue?

v4.9.x/v4.14.x kernels currently need this:

https://github.com/RobertCNelson/adafruit-beaglebone-io-python/commit/c35e4cb98a1f14c85aca7259132bcc97e93d78f8

In some situations u-boot overlays is getting stuck here:

https://github.com/RobertCNelson/adafruit-beaglebone-io-python/commit/4e180c54cfa0193da0b453f31f897d753dd9a4ea

Regards,

**Comment by silver2row** [comment]
Oh...I was discussing 4.9.x. Okay, understood.

Seth

P.S. @RobertCNelson , I will follow those protocols to get things "cracking." Thank you.
