### ISSUE TITLE
Pocket Beagle Bone Coding

### ISSUE THREAD

**Issue by Rohi23** [adafruit/adafruit-beaglebone-io-python#177]
Hello, 

We are developing a gateway  application in pocket beagle bone .

Is it better to build the project in C or Python.

**Comment by pdp7** [comment]
Currently, support for the PocketBeagle is still a work in progress. @RobertCNelson has been contributing but you may not yet want to base a project on using Adafruit_BBIO on the PocketBeagle.

**Comment by pdp7** [comment]
You may also want to ask this question on the BeagleBoard.org community mailing list to the perspective of other people, too: https://beagleboard.org/discuss#board_forum_embed
