### ISSUE TITLE
fatal error: ../../src/core.h: No such file or directory

### ISSUE THREAD

**Issue by Rohi23** [adafruit/adafruit-beaglebone-io-python#181]
Hello, 

I am new to beagle Bone. 

I have downloaded C Library for BeagleBone Black from below link. 

https://github.com/sijpesteijn/BBCLib

Added the Source and Example's 
![beaglebone](https://user-images.githubusercontent.com/32449901/32046573-1769593a-ba61-11e7-81ee-a5ea16971158.png)
 to Eclipse SRC directories as per the image. 

After building the project getting  fatal error: ../../src/core.h: No such file or directory . 

Please advice.

**Comment by pdp7** [comment]
@Rohi23 this appears to be unrelated to the Python library in this repo.  Please open an issue in https://github.com/sijpesteijn/BBCLib
