### ISSUE TITLE
GPIO is extremely slow (20ms to toggle) in 1.0.6

### ISSUE THREAD

**Issue by nickamuch** [adafruit/adafruit-beaglebone-io-python#188]
There are a bunch of syslogs scattered throughout the gpio_set_value function.  These should not be there. Removing them causes the gpio sets to run at a speed similar to what was seen in 1.0.3

**Comment by pdp7** [comment]
@nickamuch Good point.  I will remove these and publish a new version.

**Comment by pdp7** [comment]
I have created release [1.0.7](https://github.com/adafruit/adafruit-beaglebone-io-python/releases/tag/1.0.7)

**Comment by nickamuch** [comment]
Great, thank you!
