### ISSUE TITLE
Encoder: initialize only the given channel

### ISSUE THREAD

**Issue by dplanella** [adafruit/adafruit-beaglebone-io-python#200]
Currently, upon instantiating the RotaryEncoder class, a channel index can be given to initialize and use a particular eQEP channel.

On initializing the class however, all possibe channels are configured as qep, regardless of whether they are available or not. That is, the channel index is ignored and all channels are configured instead of just the given one.

Pull request #199 addresses this.

**Comment by pdp7** [comment]
Thanks @dplanella. I have merged #199
