### ISSUE TITLE
Problems with specific GPIO pins

### ISSUE THREAD

**Issue by boineg** [adafruit/adafruit-beaglebone-io-python#224]
I'm new to the Beaglebone Black platform and linux boards in general so forgive my noob mistakes and inability to debug properly. I whoever will help me will give me specific instructions as to what to do and what to specifically type in the terminal. I am coding through Putty and am logged in as debian. I have tried using sudo but nothing changes.

I'm running newly flashed Debian 9.1 2017-08-31 4GB SD LXQT and am having problems configuring specific pins, namely P8_7, P8_8. I have tested some other pins (not yet all of them) and they seem to be working fine. 

I am also able to change the state of these pins manually using "config-pin P8.08 hi" or "config-pin P8.08 low"

I am using a very simple code.
>import Adafruit_BBIO.GPIO as GPIO
GPIO.setup("P8_7", GPIO.OUT)
GPIO.output("P8_7",GPIO.HIGH)
GPIO.cleanup()

and the terminal gives me this error

> Traceback (most recent call last):
  File "gpio.py", line 5, in <module>
    GPIO.setup("P8_7", GPIO.OUT)
ValueError: Set gpio value failed, missing file or invalid permissions.

I have also tried configuring them as inputs using this code.
>import Adafruit_BBIO.GPIO as GPIO
GPIO.setup("P8_8", GPIO.IN)
GPIO.add_event_detect("P8_8", GPIO.RISING)
GPIO.cleanup()

and I get this error

> Traceback (most recent call last):
  File "gpio.py", line 3, in <module>
    GPIO.add_event_detect("P8_8", GPIO.RISING)
RuntimeError: Failed to add edge detection

EDIT: I am also experiencing a problem with P9_25, I can compile the code properly but if I set it to high in the code I dont get a 3.3V output from the actual pin.

**Comment by pdp7** [comment]
Hi @boineg, sorry for the delay. Have you tried running Python with sudo?

I've been traveling but will be home on Sunday and will try to reproduce this issue.

**Comment by pdp7** [comment]
It would be helpful if you could run strace so that I can better understand what is happening.

Install strace (if it doesn't already exist):

```sudo apt-get install strace```

Then run strace, replace test.py with the name of your test program:

```strace -f -o strace.log python test.py```

Paste the contents of strace.log into a gist.

**Comment by boineg** [comment]
Sorry for the delay as well. I solved the issue by flashing a different image.
