### ISSUE TITLE
GPIO.setup() fails on docker container

### ISSUE THREAD

**Issue by maiorfi** [adafruit/adafruit-beaglebone-io-python#225]
...because of check made in /source/common.c (https://github.com/adafruit/adafruit-beaglebone-io-python/blob/61af64e734f3f7c2ca96495cea7ea9fc78f4c877/source/common.c#L595) where library execs a grep for model string "/proc/device-tree/model". Error message is "/bin/grep: /proc/device-tree/model: No such file or directory".

I'm running beaglebone python (2) resin.io container. More info here: https://docs.resin.io/runtime/resin-base-images/#python

On container, "/proc/device-tree" is actually a symbolic link to "/sys/firmware/devicetree/base", but "/sys/firmware" doesn't exist at all.

**Comment by pdp7** [comment]
@maiorfi thanks for reporting.

@RobertCNelson any thoughts about a more robust way to check the board model?

**Comment by RobertCNelson** [comment]
@pdp7 easy give up!

If we can't read /proc/device-tree, the library should give up and spit out an error like. "Unable to detect board, please set an override in your python project: bbio_mode=BBB" Or something like that, but optional..

Regards,

**Comment by pdp7** [comment]
> I'm running beaglebone python (2) resin.io container. More info here: https://docs.resin.io/runtime/resin-base-images/#python

@maiorfi I'm not too familiar with Resin.io.  Does this mean that the container is running on the BeagleBone?  Or is it that there is a container with a BeagleBone environment running on a host computer?

**Comment by RobertCNelson** [comment]
It's yocto base, they've been building off our kernel, so feature wise it's in lock-step with us.

https://docs.resin.io/understanding/understanding-devices/2.x/

Regards,

**Comment by maiorfi** [comment]
Resin.IO provided for container images that you can run using Docker (daemon) on a physical host. In this case we are talking about using BBB as host.
So, since docker allows for "exposing" host devices (such as /dev/ttyUSB0) to containers (via --device option in "docker run" command), I am not sure one can do same thing with entire device subtrees, such as /sys/class. Maybe mapping volumes between host and container in /sys/class space?

**Comment by pdp7** [comment]
@maiorfi I would be open to the idea of adding a [special case in the code](https://github.com/adafruit/adafruit-beaglebone-io-python/blob/61af64e734f3f7c2ca96495cea7ea9fc78f4c877/source/common.c#L595) to look at an alternate path if `/proc/device-tree/model` does not exist.  Could you create a file somewhere in the filesystem with the board model?

**Comment by maiorfi** [comment]
...maybe parsing "uname -a" could be useful in order to have some hint about container hosting, but the real question is "is there anything that will prevent library from working as expected when running inside a container?"

**Comment by RobertCNelson** [comment]
@maiorfi no uname -a is not going to tell you anything about the underline hardware.  Your container should stop playing games, and just export proc.

Regards,

**Comment by maiorfi** [comment]
I guess we could ask resin.io (container images maintainer) to provide for that on their base images, but I am wondering if even skipping that check, container running python library could actually access to underlying hardware...

**Comment by RobertCNelson** [comment]
Try it:

```
cd /sys/class/pwm/pwmchip*/
echo 1 > export
cd pwm*/
echo 200000 > period
echo 100000 > duty_cycle
echo 1 > enable
```

**Comment by pdp7** [comment]
@maiorfi were you able to try the above instructions?

**Comment by pdp7** [comment]
@maiorfi were you able to try the PWM test listed above?

**Comment by pdp7** [comment]
Please reopen if this issue is still of interest
