### ISSUE TITLE
Getting position of rotary encoder by Adafruit_BBIO.Encoder

### ISSUE THREAD

**Issue by DarioushK1** [adafruit/adafruit-beaglebone-io-python#241]
Hi, I'm kinda new to beaglebones. I've used Adafruit_BBIO.Encoder to read the current position of my rotary encoder. However, the output is always 0 or -1. p8.11 and p8.12 are the pins that I've used.
Here is my code:

from Adafruit_BBIO.Encoder import RotaryEncoder, eQEP2

myEncoder = RotaryEncoder(eQEP2)

cur_position = myEncoder.position
while 1:
    print cur_position

I will appreciate if anyone can help me.

Thank you.
Darioush

**Comment by pdp7** [comment]
I'm at a conference this week but I will attempt to reproduce this issue once I return home.  Thanks.

**Comment by DarioushK1** [comment]
I solved it. Thanks.

**Comment by Shadi4772** [comment]
Hello, I'm trying to do the same and I always get 0. can you help me with your solution? Thank you in advance
