### ISSUE TITLE
how to install different kernel version

### ISSUE THREAD

**Issue by gibbypoo** [adafruit/adafruit-beaglebone-io-python#244]
> The README suggests I use kernel 4.14 and I'm on 4.9. How do I go back?

**Comment by pdp7** [comment]
To install 4.9 kernel:
```
sudo /opt/scripts/tools/update_kernel.sh --lts-4_9
```
To install 4.14 kernel:
```
sudo /opt/scripts/tools/update_kernel.sh --lts-4_14
```

**Comment by pdp7** [comment]
@gibbypoo is this still an issue for you?

**Comment by gibbypoo** [comment]
Yes, so is 4.9 okay for the API?

**Comment by pdp7** [comment]
Yes, Adafruit_BBIO should work ok with a Linux 4.9 kernel.

**Comment by gibbypoo** [comment]
That works! Any chance for an update of the readme? It reads like 4.9 isn't an option. Thanks for the quick response!
