### ISSUE TITLE
cd: /sys/devices/bone_capemgr.*: No such file or directory

### ISSUE THREAD

**Issue by sebastianimsys** [adafruit/adafruit-beaglebone-io-python#291]
Hi...Where is the "/slots" or how enable the UART ports in the BBB.
The output of command sudo /opt/scripts/tools/version.sh is:

```
root@beaglebone:~# sudo /opt/scripts/tools/version.sh git:/opt/scripts/:[e9bcff232834702c1c810710706ee815d77b080b] eeprom:[A335BNLTEIA04816BBBK28A7] model:[TI_AM335x_BeagleBone_Black] dogtag:[BeagleBoard.org Debian Image 2018-10-07] 
bootloader:[microSD-(push-button)]:[/dev/mmcblk0]:[U-Boot 2018.09-00002-gd5b4c4b656]:[location: dd MBR] 
kernel:[4.14.71-ti-r80] 
nodejs:[v6.14.4] 
uboot_overlay_options:[enable_uboot_overlays=1] 
uboot_overlay_options:[uboot_overlay_pru=/lib/firmware/AM335X-PRU-RPROC-4-14-TI-00A0.dtbo] 
uboot_overlay_options:[enable_uboot_cape_universal=1] 
pkg check: to individually upgrade run: [sudo apt install --only-upgrade <pkg>] pkg:[bb-cape-overlays]:[4.4.20180928.0-0rcnee0~stretch+20180928] 
pkg:[bb-wl18xx-firmware]:[1.20180517-0rcnee0~stretch+20180517] 
pkg:[kmod]:[23-2rcnee1~stretch+20171005] 
pkg:[librobotcontrol]:[1.0.3-git20181005.0-0rcnee0~stretch+20181005] 
pkg:[firmware-ti-connectivity]:[20170823-1rcnee1~stretch+20180328] 
groups:[debian : debian adm kmem dialout cdrom floppy audio dip video plugdev users systemd-journal i2c bluetooth netdev cloud9ide gpio pwm eqep admin spi tisdk weston-launch xenomai] 
cmdline:[console=ttyO0,115200n8 bone_capemgr.uboot_capemgr_enabled=1 root=/dev/mmcblk0p1 ro rootfstype=ext4 rootwait coherent_pool=1M net.ifnames=0 quiet] dmesg | grep pinctrl-single [ 1.185005] pinctrl-single 44e10800.pinmux: 142 pins at pa f9e10800 size 568 dmesg | grep gpio-of-helper [ 1.197159] gpio-of-helper ocp:cape-universal: ready END
```

**Comment by sebastianimsys** [comment]
Where is the "/slots" or how enable the UART ports in the BBB.
 The output of command  sudo /opt/scripts/tools/version.sh is:

`git:/opt/scripts/:[e9bcff232834702c1c810710706ee815d77b080b]
eeprom:[A335BNLTEIA04816BBBK28A7]
model:[TI_AM335x_BeagleBone_Black]
dogtag:[BeagleBoard.org Debian Image 2018-10-07]
bootloader:[microSD-(push-button)]:[/dev/mmcblk0]:[U-Boot 2018.09-00002-gd5b4c4b656]:[location: dd MBR]
kernel:[4.14.71-ti-r80]
nodejs:[v6.14.4]
uboot_overlay_options:[enable_uboot_overlays=1]
uboot_overlay_options:[uboot_overlay_pru=/lib/firmware/AM335X-PRU-RPROC-4-14-TI-00A0.dtbo]
uboot_overlay_options:[enable_uboot_cape_universal=1]
pkg check: to individually upgrade run: [sudo apt install --only-upgrade <pkg>]
pkg:[bb-cape-overlays]:[4.4.20180928.0-0rcnee0~stretch+20180928]
pkg:[bb-wl18xx-firmware]:[1.20180517-0rcnee0~stretch+20180517]
pkg:[kmod]:[23-2rcnee1~stretch+20171005]
pkg:[librobotcontrol]:[1.0.3-git20181005.0-0rcnee0~stretch+20181005]
pkg:[firmware-ti-connectivity]:[20170823-1rcnee1~stretch+20180328]
groups:[debian : debian adm kmem dialout cdrom floppy audio dip video plugdev users systemd-journal i2c bluetooth netdev cloud9ide gpio pwm eqep admin spi tisdk weston-launch xenomai]
cmdline:[console=ttyO0,115200n8 bone_capemgr.uboot_capemgr_enabled=1 root=/dev/mmcblk0p1 ro rootfstype=ext4 rootwait coherent_pool=1M net.ifnames=0 quiet]
dmesg | grep pinctrl-single
[    1.185005] pinctrl-single 44e10800.pinmux: 142 pins at pa f9e10800 size 568
dmesg | grep gpio-of-helper
[    1.197159] gpio-of-helper ocp:cape-universal: ready
END`

**Comment by sebastianimsys** [comment]
Hi...Where is the "/slots" or how enable the UART ports in the BBB.
The output of command sudo /opt/scripts/tools/version.sh is:

`root@beaglebone:~# sudo /opt/scripts/tools/version.sh
git:/opt/scripts/:[e9bcff232834702c1c810710706ee815d77b080b]
eeprom:[A335BNLTEIA04816BBBK28A7]
model:[TI_AM335x_BeagleBone_Black]
dogtag:[BeagleBoard.org Debian Image 2018-10-07]
bootloader:[microSD-(push-button)]:[/dev/mmcblk0]:[U-Boot 2018.09-00002-gd5b4c4b656]:[location: dd MBR]
kernel:[4.14.71-ti-r80]
nodejs:[v6.14.4]
uboot_overlay_options:[enable_uboot_overlays=1]
uboot_overlay_options:[uboot_overlay_pru=/lib/firmware/AM335X-PRU-RPROC-4-14-TI-00A0.dtbo]
uboot_overlay_options:[enable_uboot_cape_universal=1]
pkg check: to individually upgrade run: [sudo apt install --only-upgrade <pkg>]
pkg:[bb-cape-overlays]:[4.4.20180928.0-0rcnee0~stretch+20180928]
pkg:[bb-wl18xx-firmware]:[1.20180517-0rcnee0~stretch+20180517]
pkg:[kmod]:[23-2rcnee1~stretch+20171005]
pkg:[librobotcontrol]:[1.0.3-git20181005.0-0rcnee0~stretch+20181005]
pkg:[firmware-ti-connectivity]:[20170823-1rcnee1~stretch+20180328]
groups:[debian : debian adm kmem dialout cdrom floppy audio dip video plugdev users systemd-journal i2c bluetooth netdev cloud9ide gpio pwm eqep admin spi tisdk weston-launch xenomai]
cmdline:[console=ttyO0,115200n8 bone_capemgr.uboot_capemgr_enabled=1 root=/dev/mmcblk0p1 ro rootfstype=ext4 rootwait coherent_pool=1M net.ifnames=0 quiet]
dmesg | grep pinctrl-single
[    1.185005] pinctrl-single 44e10800.pinmux: 142 pins at pa f9e10800 size 568
dmesg | grep gpio-of-helper
[    1.197159] gpio-of-helper ocp:cape-universal: ready
END
`

**Comment by pdp7** [comment]
@sebastianimsys 
*Please visit the UART section of the README for this library*:
https://github.com/adafruit/adafruit-beaglebone-io-python/#uart

There is a no longer the cape manager driver in the Linux kernel on current BeagleBoard.org Debian images by @RobertCNelson.  Therefore, the slots file no longer exists in /sys.


https://elinux.org/Beagleboard:BeagleBoneBlack_Debian#Where_did_the_slots_file_go.3F

> Kernel Overlays are going bye-bye, too many bugs, too many race conditions, no kernel maintainers interested. We've said our farewells and U-Boot Overlays is the way forward: https://elinux.org/Beagleboard:BeagleBoneBlack_Debian#U-Boot_Overlays With multiple parties working on the U-Boot infrastructure.

**Comment by sebastianimsys** [comment]
Now i have a new problem, i want to use a GPRS module Sara-u201 whit yhis tutorial: https://learn.adafruit.com/fona-tethering-to-raspberry-pi-or-beaglebone-black/usage

When i used this command "cat /var/log/syslog | grep pppd" my output is:
`debian@beaglebone:~$ cat /var/log/syslog | grep pppd
`
`Binary file (standard input) matches`

**Comment by RobertCNelson** [comment]
@sebastianimsys if you need a uart at bootup for this module, use one of the uart u-boot overlays that matches the pins you are using..

for example: P9.24 P9.26: https://github.com/beagleboard/bb.org-overlays/blob/master/src/arm/BB-UART1-00A0.dts

But we don't know what pins you want to use..

Regards,

**Comment by RobertCNelson** [comment]
@sebastianimsys this is ancient:

> When i used this command "cat /var/log/syslog | grep pppd" my output is:
> `debian@beaglebone:~$ cat /var/log/syslog | grep pppd `
> `Binary file (standard input) matches`

Use:

```bash
journalctl | grep pppd
```

**Comment by RobertCNelson** [comment]
@sebastianimsys you need a uart at bootup for this module, use one of the uart u-boot overlays that matches the pins you are using..

for example: P9.24 P9.26: https://github.com/beagleboard/bb.org-overlays/blob/master/src/arm/BB-UART1-00A0.dts

But we don't know what pins you want to use..

Regards,

**Comment by sebastianimsys** [comment]
I'm using P9_24 and P9_26, sorry but i don't really understand...This link "https://github.com/beagleboard/bb.org-overlays/blob/master/src/arm/BB-UART1-00A0.dts" shows a scrip, but what i do with that scrip? i must copy it in some folder of the BBB?

**Comment by RobertCNelson** [comment]
@sebastianimsys in /boot/uEnv.txt set:

```bash
uboot_overlay_addr0=/lib/firmware/BB-UART1-00A0.dtbo
```
Now P9.24/P9.26 will be an active uart on bootup. Then run your "sudo pon fona" script, making sure it talks to the correct usart...

Regards,

**Comment by sebastianimsys** [comment]
I copy  

`uboot_overlay_addr0=/lib/firmware/BB-UART1-00A0.dtbo`  

on the bottom of uEnv.txt and run "sudo pon fano" and no work,  so i use the commands to configure pin 

`config-pin P9.24 uart  # UART1_TXD`
`config-pin P9.26 uart  # UART1_RXD `

and the answer to those commands are:

`P9_24 pinmux file not found!`
`bash:/sys/devices/platform/ocp/ocp*P9_24_pinmux/state: No such file or directory`

**Comment by RobertCNelson** [comment]
@sebastianimsys correct..

```bash
uboot_overlay_addr0=/lib/firmware/BB-UART1-00A0.dtbo
```
Hard "CODES"...
```bash
config-pin P9.24 uart # UART1_TXD
config-pin P9.26 uart # UART1_RXD
```
Something is wrong with your "fano" script, do you have the source?

Regards,

**Comment by sebastianimsys** [comment]
Yeah, I'm using the code of this page : "https://learn.adafruit.com/fona-tethering-to-raspberry-pi-or-beaglebone-black/setup"

`connect "/usr/sbin/chat -v -f /etc/chatscripts/gprs -T internet.comcel.com.co"
`
`/dev/ttyO1
`
`115200
`
`noipdefault
`
`usepeerdns
`
`defaultroute
`
`persist
`
`noauth
`
`nocrtscts
`
`local
`

that the code without comments, also try with the UART4 but doesn't work too

**Comment by pdp7** [comment]
@sebastianimsys are you still having an issue? thanks
