### ISSUE TITLE
Fail to set P8-3 as GPIO input

### ISSUE THREAD

**Issue by AndyLAN99** [adafruit/adafruit-beaglebone-io-python#292]
I use the following to  initialise the P8_3 to GPIO input, it will fail 
"
import Adafruit_BBIO.GPIO as GPIO
from time import sleep
import Adafruit_BBIO.ADC as ADC

GPIO.setup("P8_3,GPIO.IN)
"
and shows "
ValueError: Set gpio mode failed, missing file or invalid permissions.
"

but if i initialise the P8_3 to be output, 
"GPIO.setup("P8_3,GPIO.OUT)"
it succeeds.

How can I configure P8_3 to be GPIO input?

my software version information is like following: 

debian@beaglebone:~$ sudo /opt/scripts/tools/version.sh
[sudo] password for debian: 
git:/opt/scripts/:[1aa73453b2c980b75e31e83dab7dd8b6696f10c7]
eeprom:[A335BNLTBBG1BBG217071852]
model:[TI_AM335x_BeagleBone_Green]
dogtag:[BeagleBoard.org Debian Image 2018-10-07]
bootloader:[microSD-(push-button)]:[/dev/mmcblk0]:[U-Boot 2018.09-00002-gd5b4c4b656]:[location: dd MBR]
kernel:[4.14.71-ti-r80]
uboot_overlay_options:[enable_uboot_overlays=1]
uboot_overlay_options:[disable_uboot_overlay_emmc=1]
uboot_overlay_options:[disable_uboot_overlay_video=1]
uboot_overlay_options:[disable_uboot_overlay_audio=1]
uboot_overlay_options:[disable_uboot_overlay_wireless=1]
uboot_overlay_options:[uboot_overlay_pru=/lib/firmware/AM335X-PRU-RPROC-4-14-TI-00A0.dtbo]
uboot_overlay_options:[enable_uboot_cape_universal=1]
uboot_overlay_options:[dtb_overlay=/lib/firmware/univ-all-00A0.dtbo]
pkg check: to individually upgrade run: [sudo apt install --only-upgrade <pkg>]
pkg:[bb-cape-overlays]:[4.4.20181019.0-0rcnee0~stretch+20181019]
pkg:[bb-wl18xx-firmware]:[1.20180517-0rcnee0~stretch+20180517]
pkg:[kmod]:[23-2rcnee1~stretch+20171005]
pkg:[librobotcontrol]:[1.0.3-git20181009.0-0rcnee0~stretch+20181010]
pkg:[firmware-ti-connectivity]:[20170823-1rcnee1~stretch+20180328]
groups:[debian : debian adm kmem dialout cdrom floppy audio dip video plugdev users systemd-journal i2c bluetooth netdev cloud9ide gpio pwm eqep admin spi tisdk weston-launch xenomai]
cmdline:[console=ttyO0,115200n8 root=/dev/mmcblk0p1 ro rootfstype=ext4 rootwait coherent_pool=1M net.ifnames=0 quiet]
dmesg | grep pinctrl-single
[    1.049848] pinctrl-single 44e10800.pinmux: 142 pins at pa f9e10800 size 568
dmesg | grep gpio-of-helper
[    1.051011] gpio-of-helper ocp:cape-universal: ready
END

**Comment by pdp7** [comment]
@AndyLAN99 
please try this:
`config-pin -q p8.3`
`config-pin -l p8.3`

**Comment by AndyLAN99** [comment]
debian@beaglebone:~$ config-pin -q p8.3
P8_03 pinmux file not found!
Pin has no cape: P8_03
debian@beaglebone:~$ config-pin -l p8.3
default gpio gpio_pu gpio_pd gpio_input

**Comment by AndyLAN99** [comment]
after I update the bootloader and correct the pru overlayer, it works well.
Refer to:
https://github.com/beagleboard/bb.org-overlays/issues/76
