### ISSUE TITLE
Dead link in source code comment

### ISSUE THREAD

**Issue by KevinWMatthews** [adafruit/adafruit-beaglebone-io-python#296]
Small thing - this link to jadonk's `bone.js` is dead:
https://github.com/adafruit/adafruit-beaglebone-io-python/blob/e96e1efb53b3dc225567f4aec3173edc0829b8db/source/common.c#L72

 Looks like their directory structure changed between [v0.2.4](https://github.com/jadonk/bonescript/tree/0.2.4/node_modules/bonescript/bone.js) and [v0.2.5](https://github.com/jadonk/bonescript/tree/0.2.5/src/bone.js).

You have a similar link that still works here:

https://github.com/adafruit/adafruit-beaglebone-io-python/blob/e96e1efb53b3dc225567f4aec3173edc0829b8db/source/common.c#L287

One solution is to link to a tagged version, such as:
https://github.com/jadonk/bonescript/blob/0.7.0/src/bone.js

**Comment by pdp7** [comment]
@KevinWMatthews thanks for pointing this out.
