### ISSUE TITLE
only 5 PWM pins possible at a time

### ISSUE THREAD

**Issue by malcolmputer** [adafruit/adafruit-beaglebone-io-python#31]
Using Angstrom, any of the PWM pin pairs (say "9_14" and "9_16") are not available to be used at the same time.

I believe the actual hardware limitation here is that you must use the same frequency on the two pins, but you may have a different duty cycle. 

BBIO does not seem to enable the pins even though the hardware should allow it. 

This only allows the use of 5 PWM pins at the same time even after disabling HDMI.

Try for instance:
PWM.start("P9_16", 50, 25000, 1)
PWM.start("P9_22", 50, 25000, 1)
PWM.start("P9_28", 50, 25000, 1)
PWM.start("P9_42", 50, 25000, 1)
PWM.start("P8_13", 50, 25000, 1) 

Then try to enable either "P8_34" or "P8_19", and the script will look like it is working, and even add the line to the slots file, but a scope reading will confirm otherwise.

**Comment by pdp7** [comment]
@malcolmputer there were several PWM improvements in #108.  Could you please check if this is still an issue with the latest version?
