### ISSUE TITLE
GPIO callback causing segmentation fault

### ISSUE THREAD

**Issue by guilhermearaujo** [adafruit/adafruit-beaglebone-io-python#42]
I am attempting to perform some tasks on a rising edge of the P8 14, but everytime after the callback function ends, there's a segmentation fault and the script stops.

The following counter in incremented, the line is properly printed, but right after that comes the error message.

``` python
import Adafruit_BBIO.GPIO as GPIO

counterX = 0

def updateEncoderX(channel):
    global counterX
    counterX = counterX + 1
    print "Encoder counter updated: %d" % counterX

GPIO.setup("P8_14", GPIO.IN)
GPIO.add_event_detect("P8_14", GPIO.RISING, callback=updateEncoderX)

try:
    while 1:
        pass

except KeyboardInterrupt:
    GPIO.cleanup()
GPIO.cleanup()
```

**Comment by UpolRys** [comment]
I have some kind of similar issue. I hope it will be okey if I reopen this issue. Or should I open another issue?
