### ISSUE TITLE
Internal pull down resistors are always enabled

### ISSUE THREAD

**Issue by fabiengagne** [adafruit/adafruit-beaglebone-io-python#5]
The parameter "pull_up_down" to GPIO.setup() has no effect. The mode of the input pins always remain set to pull-down mode.

This can be observed by connecting a 100k ohm resistor to 3.3V and the other end to an input pin, such as P8_16. 

If the internal pull down is disabled (by specifying pull_up_down=GPIO.PUD_NONE), a voltmeter on P8_16 should read close to 3.3V. However, the voltage is significantly lower (nearly 1 volt lower), as it could be explained by an internal pull down resitor. Changing the pull_up_down mode to GPIO.PUD_UP or GPIO.PUD_NONE has no effect on voltage.

import Adafruit_BBIO.GPIO as GPIO
import time

GPIO.setup("P8_16", GPIO.IN, pull_up_down=GPIO.PUD_DOWN)
print "P8_16 set to pull down mode"
time.sleep(4.0)

GPIO.setup("P8_16", GPIO.IN, pull_up_down=GPIO.PUD_UP)
print "P8_16 set to pull up mode"
time.sleep(4.0)

GPIO.setup("P8_16", GPIO.IN, pull_up_down=GPIO.PUD_NONE)
print "P8_16 disabled internal resistor"
time.sleep(4.0)

**Comment by MrBillium** [comment]
Any update on this issue - I would like to avoid using Bonescript to set Inputs to pullup

**Comment by MrBillium** [comment]
Let me revise my last comment. Bonescript is a really nice way to do this! 
As soon as I dug into the code I realized that bonescript creates .dts and .dtbo files on the fly.
So to set P8_14 to input with pullup just go to 192.168.7.2, Bonescript, Pinmode and edit the script to say b.pinMode("P8_14", b.INPUT_PULLUP);
when you run it the BB will set the pin and the overlay is created and compiled as if you did it yourself!
 Now all you have to do is look in /sys/firmware for the exact filename it created and put something like  this in your startup script
sudo /echo bspm_P8_14_37 > /sys/devices/bone_capemgr.9/slots
Now the new overlay will load each time the BB starts.
Bill

**Comment by pdp7** [comment]
@fabiengagne could you please check if this is still an issue in the latest version?

**Comment by fabiengagne** [comment]
I haven't used the beaglebone in quite a while.

**Comment by skjortan23** [comment]
This is still e problem in the latest version... i can not get the pull up or downs to work on any gpio pins.

**Comment by skjortan23** [comment]
Steps to reproduce.
`
import Adafruit_BBIO.GPIO as GPIO
GPIO.setup('P8_11', GPIO.IN, pull_up_down=GPIO.PUD_UP)
`
meassure on the pin which is still low

**Comment by pdp7** [comment]
@skjortan23 Could you let me know which image you are using? 
```
uname -a 
cat /etc/dogtag 
cat /etc/debian_version 
cat /sys/devices/platform/bone_capemgr/slots 
cat /proc/cmdline
```

**Comment by skjortan23** [comment]
Thank you for looking into this 


ubuntu@11:~$ uname -a 
Linux 11 4.4.59-ti-r96 #1 SMP Tue Apr 4 17:50:34 UTC 2017 armv7l armv7l armv7l GNU/Linux/devices/platform
/bone_capemgr/slots 
cat /proc/cmdlineubuntu@movoi11:~$ cat /etc/dogtag 
rcn-ee.net console Ubuntu Image 2017-04-07
ubuntu@11:~$ cat /etc/debian_version 
stretch/sid
ubuntu@i11:~$ cat /sys/devices/platform/bone_capemgr/slots 
 0: PF----  -1 
 1: PF----  -1 
 2: PF----  -1 
 3: PF----  -1 
ubuntu@11:~$ cat /proc/cmdline
console=ttyO0,115200n8 root=/dev/mmcblk0p1 ro rootfstype=ext4 rootwait coherent_pool=1M net.ifnames=0 quiet

**Comment by pdp7** [comment]
@skjortan23 would you be able to try the most recent [Debian Jessie image from BeagleBoard.org](http://beagleboard.org/latest-images) to check if this issue still occurs?  h

**Comment by pdp7** [comment]
@skjortan23 could you please post `/boot/uEnv.txt`?

**Comment by pdp7** [comment]
I believe I have just tested pull up and pull down OK.

## P8_11 disconnected
```
debian@beaglebone:~$ sudo python input.py
0
debian@beaglebone:~$ sudo python input-pull-up.py
1
debian@beaglebone:~$ sudo python input-pull-down.py
0
```

## P8_11 connected to 3.3V
```
debian@beaglebone:~$ sudo python input.py
1
debian@beaglebone:~$ sudo python input-pull-up.py
1
debian@beaglebone:~$ sudo python input-pull-down.py
1
```

## P8_11 connected to GND
```
debian@beaglebone:~$ sudo python input.py
0
debian@beaglebone:~$ sudo python input-pull-up.py
0
debian@beaglebone:~$ sudo python input-pull-down.py
0

```


## input.py
```
import Adafruit_BBIO.GPIO as GPIO

GPIO.setup('P8_11', GPIO.IN)
print GPIO.input('P8_11')
```

## input-pull-up.py
```
import Adafruit_BBIO.GPIO as GPIO

GPIO.setup('P8_11', GPIO.IN, pull_up_down=GPIO.PUD_UP)
print GPIO.input('P8_11')
```

## input-pull-down.py
```
import Adafruit_BBIO.GPIO as GPIO

GPIO.setup('P8_11', GPIO.IN, pull_up_down=GPIO.PUD_DOWN)
print GPIO.input('P8_11')
```

**Comment by fabiengagne** [comment]
You may just have picked noise while reading the pin.

Try the procedure documented in post 1.

**Comment by pdp7** [comment]
@fabiengagne thanks for the suggestion.  I will try it tonight and share my results.

**Comment by skjortan23** [comment]
@pdp7 i have not have had the time to test with the latest debian image. I will try this over the weekend. 
I have worked around the issue by loading a custom .dtbo file at boot.

**Comment by pdp7** [comment]
I used `config-pin` to set the pinmux on `P8.16` and measured the voltage:
```
root@beaglebone:~# config-pin P8.16 default
root@beaglebone:~# # 0.002 V from P8.16 to ground
root@beaglebone:~# config-pin P8.16 gpio
root@beaglebone:~# # 0.745 V from P8.16 to ground
root@beaglebone:~# config-pin P8.16 gpio_pu
root@beaglebone:~# # 3.209 V from P8.16 to ground
root@beaglebone:~# config-pin P8.16 gpio_pd
root@beaglebone:~# # 0.002 V from P8.16 to ground
```

Do you get the same results?

**Comment by pdp7** [comment]
Here the results when running the script below:
* `P8_16 set to pull down mode`
   * 0.002 V from P8.16 to ground
* `P8_16 set to pull up mode`
   * 3.208 V from P8.16 to ground
* `P8_16 disabled internal resistor`
   * 0.7046 V from P8.16 to ground





## gpio-test.py
```
import Adafruit_BBIO.GPIO as GPIO
import time

GPIO.setup("P8_16", GPIO.IN, pull_up_down=GPIO.PUD_DOWN)
print "P8_16 set to pull down mode"
time.sleep(4.0)

GPIO.setup("P8_16", GPIO.IN, pull_up_down=GPIO.PUD_UP)
print "P8_16 set to pull up mode"
time.sleep(4.0)


# from source/event_gpio.h
#  #define PUD_OFF  0
#  #define PUD_DOWN 1
#  #define PUD_UP   2


GPIO.setup("P8_16", GPIO.IN, pull_up_down=GPIO.PUD_OFF)
print "P8_16 disabled internal resistor"
time.sleep(4.0)
```

**Comment by fabiengagne** [comment]
Thanks. It really appears to be fixed. If we all agree, we shall close this issue.
