### ISSUE TITLE
SPI writebytes / xfer / xfer2 clocks out arrays of bytes in reverse order

### ISSUE THREAD

**Issue by sidechained** [adafruit/adafruit-beaglebone-io-python#52]
Just wanted to open this as a separate issue, as I'm experiencing the same behaviour as tweekzilla as mentioned here:

https://github.com/adafruit/adafruit-beaglebone-io-python/issues/47

That is, that executing spi.writebytes([0x44, 0x88, 0xBB, 0xDD]) clocks out in reverse order (i.e. 0xDD, 0xBB, 0x44, 0x88). I can confirm the same behaviour with xfer and xfer2. Is this a problem with the spidev C++ implementation, or with the bindings?

**Comment by pdp7** [comment]
@sidechained Could you please try again with the latest version and report if this is still an issue?
