### ISSUE TITLE
spi xfer method with bpw>8 locks the system

### ISSUE THREAD

**Issue by redFrik** [adafruit/adafruit-beaglebone-io-python#60]
running the latest debian bbb image (bone-debian-7.4-2014-03-27-2gb.img) and an A5C board, the spi xfer method with 12bit wordlength freezes the computer.

debian@beaglebone:~$ sudo python
Python 2.7.3 (default, Mar 14 2014, 17:55:54) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from Adafruit_BBIO.SPI import SPI
>>> spi= SPI(0, 0)
>>> spi.bpw= 12
>>> spi.xfer([10, 20, 30])
!!!here the system completely locks up!!!

**Comment by pdp7** [comment]
@redFrik could you please try again with the latest version of adafruit-beaglebone-io-python and the latest Debian Wheezy or Jessie image from: http://beagleboard.org/latest-images

**Comment by JayWern** [comment]
@pdp7: I have the same Issue. With the latest image (Debian 8.4 2016-05-13) I got the following error now:

```
Traceback (most recent call last):
File "spi_test.py", line 2, in <module>
   spi= SPI(0, 0)
IOError: [Errno 2] No such file or directory: '/slots'
```
Any idea?

**Comment by pdp7** [comment]
@JayWern could you please specify what kernel you are using?

Paste the output of:
```
uname -a
```
