### ISSUE TITLE
PWM segfaults with multiple calls to PWM.start()

### ISSUE THREAD

**Issue by pingswept** [adafruit/adafruit-beaglebone-io-python#65]
This is with version 0.0.20 of the library.

If I execute this script on a Beaglebone Black running Debian:

    import time
    import Adafruit_BBIO.PWM as PWM

    while(1):
        PWM.start("P9_14", 50)
        PWM.start("P9_14", 50)
        time.sleep(5);
        PWM.stop("P9_14")
        time.sleep(5);

the PWM signal looks good for the first 30 seconds (3 loop iterations), and then the script hangs. The fourth burst of square waves is not emitted, and the script cannot be exited with Ctrl-C.

If I do the same at a console, I see:

    >>> import Adafruit_BBIO.PWM as PWM
    >>> PWM.start("P9_14", 50)
    >>> PWM.start("P9_14", 50)
    >>> PWM.stop("P9_14")
    >>> PWM.start("P9_14", 50)
    >>> PWM.start("P9_14", 50)
    [1]    1201 segmentation fault  python

If I execute the script under GDB, the PWM fails after three cycles, but doesn't segfault. If I interrupt the script after 3 cycles with Ctrl-C, I see:

    pwm_disable (key=0xbefff88c "P9_14") at source/c_pwm.c:241

The offending line of code is https://github.com/adafruit/adafruit-beaglebone-io-python/blob/master/source/c_pwm.c#L241

My hunch is that we're inadvertently getting trapped in the `while (pwm != NULL)` loop, but I don't understand the code well enough to be sure.

Please let me know if there is more I can do to help debug. Also, I should add that, yeah, it's stupid to call PWM.start() twice in a row, but I spend a lot of time teaching beginners this stuff; it would be nice to be robust enough to not segfault in the hands of non-experts.

**Comment by pdp7** [comment]
@pingswept  There have been several PWM improvements now merged from #108. Please try again and report if this is still an issue.
