### ISSUE TITLE
Segmentation fault on event

### ISSUE THREAD

**Issue by ChazTuna** [adafruit/adafruit-beaglebone-io-python#70]
Any help with this?  Here's the gdb bt: (running on BBB, python 2.7.3)

Python setup:
GPIO.add_event_detect(IRQpin, GPIO.RISING)
GPIO.add_event_callback(IRQpin, irqService, 0)

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xb6b17470 (LWP 12828)]
run_callbacks (gpio=48) at source/event_gpio.c:371
371             if (cb->gpio == gpio)
(gdb) bt
#0  run_callbacks (gpio=48) at source/event_gpio.c:371
#1  0xb6bcfb1a in poll_thread (threadarg=<optimized out>) at source/event_gpio.c:453
#2  0xb6fbdebc in start_thread () from /lib/arm-linux-gnueabihf/libpthread.so.0
#3  0xb6ecc0e8 in ?? () from /lib/arm-linux-gnueabihf/libc.so.6
#4  0xb6ecc0e8 in ?? () from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

**Comment by pdp7** [comment]
@ChazTuna is this still an issue?

**Comment by ChazTuna** [comment]
@pdp7 I implemented another way. Sorry :)
