### ISSUE TITLE
Python.h in source dir

### ISSUE THREAD

**Issue by peidong** [adafruit/adafruit-beaglebone-io-python#85]
Hello, I find it no "Python.h" in [common.c](https://github.com/adafruit/adafruit-beaglebone-io-python/blob/master/source/common.c#L31)

**Comment by cnobile2012** [comment]
Mr. Chen,

This is an error you get if you do not have the the Python development
libraries installed on your machine. I don't know what platform you are
using, but the package manager on your system should provide a way to find
the correct package and install it. Then just install and compile the
package again and it should work.

~Carl


On Fri, Nov 27, 2015 at 6:47 PM, Peidong Chen <notifications@github.com>
wrote:

> Hello, I find it no "Python.h" in common.c
> <https://github.com/adafruit/adafruit-beaglebone-io-python/blob/master/source/common.c#L31>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adafruit/adafruit-beaglebone-io-python/issues/85>.
>



-- 
-------------------------------------------------------------------------------
Carl J. Nobile (Software Engineer)
carl.nobile@gmail.com
-------------------------------------------------------------------------------

**Comment by SimplicityGuy** [comment]
To clarify, you need to do the following:
```
sudo apt-get install -yy build-essential python-dev
```

**Comment by pdp7** [comment]
@peidong are you still having an issue?
