### ISSUE TITLE
PWM Driving a Piezo buzzer

### ISSUE THREAD

**Issue by MrYsLab** [adafruit/adafruit-beaglebone-io-python#91]
I am trying to drive a piezo buzzer and be able to set the output frequency. Basically I can do that, but when I first do a PWM.start, I always get the same brief tone out. 

If I use any of the following 3 lines to start the pwm,

PWM.start("P9_14)

or

PWM.start("P9_14", 0)

or 

PWM.start("P9_14", 100)

I get a brief beep and then I can change the frequency.

 I want to suppress that brief beep. How would I do that?

**Comment by pdp7** [comment]
Please try again now that #108 has been merged.
