### ISSUE TITLE
Adafruit_BBIO / I2C open source license question

### ISSUE THREAD

**Issue by spmaniato** [adafruit/adafruit-beaglebone-io-python#92]
Quick question / remark: 

The `Adafruit_I2C` Python module imports `smbus` (python-smbus package), which is licensed under GPLv2, since it's based on `i2c-dev`. Doesn't that mean that `Adafruit_BBIO` as a whole has to be licensed under GPLv2 or v3 as opposed to MIT?

To be clear, I'm not criticizing or anything  :smile: I'm just interested in using `Adafruit_BBIO` in proprietary code for commercial purposes, which is why I'm investigating licensing issues. Thanks!

**Comment by ladyada** [comment]
we'll look into it! it may be required to be under GPL, but we're also looking to migrate off of smbus because its not as flexible as we need (no ETA)
