### ISSUE TITLE
not an issue, but a doubt

### ISSUE THREAD

**Issue by iamharshit** [adafruit/adafruit-beaglebone-io-python#93]
i wanted to read the rpm of my motor using an rpm encoder but that requires the use of timer interrupt and external interrupt ( since an rpm encoder sends a pulsating data ) , but i couldn't a timer and external interrupt in Adafruit library, please guide me where to look at.

**Comment by pdp7** [comment]
@iamharshit Is this still an issue for you?

If so, please post the code you are trying to get working.
